name: Build and Update README

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: npm install and build
      run: |
        npm install
        npm run build --if-present
    - name: Zip artifact
      run: Compress-Archive -Path * -DestinationPath node-app.zip -Force
      shell: pwsh
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: node-app.zip

  update-readme:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.PAT_TOKEN }}
    - name: Check for changes
      id: check_changes
      run: |
        git fetch origin main
        git diff --name-only origin/main HEAD > changes.txt
        if ! grep -q README.md changes.txt && [ -s changes.txt ]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi
    - name: Update README
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git merge origin/main
        echo "# Teacherhelper" > README.md
        echo "" >> README.md
        echo "Last updated: $(date)" >> README.md
        echo "" >> README.md
        echo "This project was successfully built." >> README.md
        echo "" >> README.md
        echo "Changes in this update:" >> README.md
        git diff --name-only origin/main HEAD | grep -v README.md >> README.md
    - name: Commit and push if changed
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --global user.email "github-actions@example.com"
        git config --global user.name "GitHub Actions"
        git add README.md
        git commit -m "Update README with latest changes" || echo "No changes to commit"
        git push origin main || (git pull --rebase origin main && git push origin main)
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    - name: Check for push errors
      if: failure()
      run: |
        echo "Push failed. Current git status:"
        git status
        echo "Remote branches:"
        git ls-remote --heads origin
        echo "Local branches:"
        git branch -v
        echo "Last few commits:"
        git log --oneline -n 5
