name: Build and Update README

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: npm install and build
      run: |
        npm install
        npm run build --if-present
    - name: Zip artifact
      run: Compress-Archive -Path * -DestinationPath node-app.zip -Force
      shell: pwsh
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: node-app
        path: node-app.zip

  update-readme:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT_TOKEN }}
    - name: Update README
      run: |
        echo "# Teacherhelper" > README.md
        echo "" >> README.md
        echo "Last updated: $(date)" >> README.md
        echo "" >> README.md
        echo "This project was successfully built." >> README.md
    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions@example.com"
        git config --global user.name "GitHub Actions"
        git add README.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update README" && git push)
